# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Compile Test

on:
  push:
    branches:
      - stable

jobs:
  compile:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: 
          - 12.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test compile
        run: yarn run build && rm -rf dist/
